### ISSUE TITLE
How to calculate Jacobian matrix?

### ISSUE THREAD

**Issue by Carol1117** [vccimaging/DiffDeflectometry#1]
Torch.autograd.grad just gives the result of Jacobian Vector Product. I can not unstrstand how to get the Jacobian matrix from Jacobian Vector Product?

![image](https://user-images.githubusercontent.com/38419870/173348456-1f6038d4-bb58-4cdd-9387-3d9972583edf.png)

**Comment by CongliWANG** [comment]
It is true that the`torch.autograd.grad` only provides the Jacobian-vector product (JVP).  In math:
$$
JVP = J @ v,
$$
where @ is matrix-vector multiplication, J is the target Jacobian matrix we want, and v is the input vector.

The Jacobian matrix can be obtained, column-wisely, by repeatedly evaluating the JVP, by poking every index of the input vector.  The following lines demonstrate this procedure:

https://github.com/vccimaging/DiffDeflectometry/blob/c30fb27b405ed3203a218b91f9a34f3d9e999f8b/diffmetrology/solvers.py#L157-L167

where:
- An empty (all zeros) Jacobian matrix J and a vector v are first constructed.
- In the for loop, poking the vector v at a different  index, e.g. v = [1, 0, 0, 0, ...].
- Evaluate JVP, this will provide, e.g. the 1st column of the matrix J.
- Reset the vector v to be all zeros and proceed to the next index, i.e. v = [0, 1, 0, 0, ...] and evaluate the 2nd column of J.

The data structure of J is not necessarily a two-dimensional torch array, but a multi-dimensional array.  This does not matter linear algebraic speaking and can be unfolded later.

Hope this is clear.

**Comment by Carol1117** [comment]
Thank you for your wonderful answer, but I may not have made my question clear. Why is the result of this function a Jacobian matrix? I can't understand the principle behind it.
![image](https://user-images.githubusercontent.com/38419870/173474901-c43ad1e6-a31f-4b21-8662-6d0729b24455.png)
Looking forward to your reply! Thank you very much!

**Comment by CongliWANG** [comment]
OK, now I understand the real concern.

This is known as the "twice autograd trick" to compute the forward-mode derivatives, using a backward-mode autodiff engine.  See the following links for more info:

[1] https://github.com/pytorch/pytorch/issues/10223#issuecomment-547104071
[2] https://j-towns.github.io/2017/06/12/A-new-trick.html

Briefly speaking, PyTorch (at the time of writing) supports only backward-mode autodiff, and the actual derivatives evaluated are VJPs.  However, we are interested in the Jacobians, and thus need JVPs instead.  But as said PyTorch is a backward-mode autodiff engine and does not support JVP out-of-the-box.

The "twice autograd trick" [2] is the saver:

- The 1st autograd (your 1st red box): It first constructs a computational graph (i.e. g(v) in [2]).
- The 2nd autograd (your 2nd red box): Then back-propagate again on the new function to obtain the JVP (i.e. the last equation in [2]).  Now you need to evaluate that column-wisely to get the Jacobian matrix constructed.

**Comment by Carol1117** [comment]
Thank you very much ! Now, I have solved my problem!
By the way
My company (www.sunnyoptical.com) has interst in "end to end joint optimization by differential ray tracing", in order to design the opitcal lens. And we are looking for the technical advisor, preferably Chinese. I have read several of your articles and feel that you are very suitable. If you are intersted in cooperating with my company, can I send more information to your email (congli.wang@kaust,edu,sa)?

**Comment by CongliWANG** [comment]
Good.  If the response resolves the issue could you please close it?

Sure we can discuss more details through emails.  Also, please CCing other co-authors as well.

**Comment by CongliWANG** [comment]
Good.  I will close this issue.

Sure we can discuss more details through emails.

**Comment by CongliWANG** [comment]
@Carol1117  I haven't received the email.  Could you send the information to:
```
congli.wang@kaust.edu.sa
```
and
```
congli.wang@berkeley.edu
```
Thanks.
